import { TimelineEvent, PollingPlace } from "./types";

export const VOTER_STEPS = [
  { id: 1, label: "Eligibility", description: "Confirm you meet voting requirements", icon: "shield-check" },
  { id: 2, label: "Registration", description: "Register or verify your registration", icon: "user-check" },
  { id: 3, label: "Verification", description: "Confirm registration status", icon: "badge-check" },
  { id: 4, label: "Polling Place", description: "Find your polling location", icon: "map-pin" },
  { id: 5, label: "Voting", description: "Cast your ballot", icon: "vote" },
];

export const TIMELINE_EVENTS: TimelineEvent[] = [
  {
    id: "1",
    title: "Voter Registration Deadline (Form 6)",
    description: "Last day to apply for new voter registration before the elections.",
    date: "2026-03-15",
    category: "registration",
    isPast: true,
    isCurrent: false,
  },
  {
    id: "2",
    title: "Publication of Final Electoral Roll",
    description: "Verification of your name in the final published voter list.",
    date: "2026-04-05",
    category: "registration",
    isPast: true,
    isCurrent: false,
  },
  {
    id: "3",
    title: "Home Voting Request Deadline (Form 12D)",
    description: "Last day for PwD and 85+ senior citizens to request home voting.",
    date: "2026-04-15",
    category: "deadline",
    isPast: false,
    isCurrent: true,
  },
  {
    id: "4",
    title: "Polling Day",
    description: "Phase 1 polling day – booths open 7:00 AM to 6:00 PM.",
    date: "2026-05-10",
    category: "election",
    isPast: false,
    isCurrent: false,
  },
  {
    id: "5",
    title: "Counting of Votes",
    description: "Official counting day and declaration of results by the ECI.",
    date: "2026-06-04",
    category: "result",
    isPast: false,
    isCurrent: false,
  },
];

export const MOCK_POLLING_PLACES: PollingPlace[] = [
  {
    id: "1",
    name: "Kendriya Vidyalaya, RK Puram Sector 4",
    address: "Room 101, Ground Floor",
    city: "New Delhi",
    state: "Delhi",
    zip: "110022",
    distance: 0.4,
    waitTime: 10,
    isOpen: true,
    hours: "7:00 AM – 6:00 PM",
    lat: 28.5677,
    lng: 77.1724,
  },
  {
    id: "2",
    name: "Govt Sarvodaya Vidyalaya",
    address: "Vasant Vihar",
    city: "New Delhi",
    state: "Delhi",
    zip: "110057",
    distance: 1.2,
    waitTime: 25,
    isOpen: true,
    hours: "7:00 AM – 6:00 PM",
    lat: 28.5583,
    lng: 77.1643,
  },
  {
    id: "3",
    name: "Municipal Corporation Primary School",
    address: "Hauz Khas Village",
    city: "New Delhi",
    state: "Delhi",
    zip: "110016",
    distance: 2.1,
    waitTime: 0,
    isOpen: false,
    hours: "Closed today",
    lat: 28.5540,
    lng: 77.1945,
  },
];

export const CIVIC_COLORS = {
  primary: "#002855",
  primaryContainer: "#002855",
  secondary: "#bb0024",
  secondaryContainer: "#e41d35",
  tertiary: "#00152c",
  background: "#f7fafc",
  surface: "#f7fafc",
  onPrimary: "#ffffff",
  outline: "#747780",
  outlineVariant: "#c4c6d0",
};
